Book.create(title: "Lord of the Rings")
Book.create(title: "Harry Potter")
Book.create(title: "Of Mice and Men")
Book.create(title: "The Tempest")
Book.create(title: "Romeo and Juliet")
Book.create(title: "Moby Dick")

Genre.create(name: "Fantasy")
Genre.create(name: "Fiction")
Genre.create(name: "Non-Fiction")
Genre.create(name: "Historial Fiction")

Author.create(name: "Tom")
Author.create(name: "Beth")
Author.create(name: "Tony")
Author.create(name: "Andy")
Author.create(name: "Kristie")
Author.create(name: "JKR")

User.create(name: "James")
User.create(name: "Brigit")